version: "3.7"

services:
  backend:
    container_name: backend_container
    restart: always
    build: ./backend
    ports:
      - "5001:5000"
    depends_on:
      - mongo
    # volumes:
    #   - ".:/app"
    #   - "/app/node_modules"
    
  frontend:
    container_name: frontend_container
    restart: always
    build: ./frontend
    depends_on:
      - backend
    # volumes:
    #   - ".:/app"
    #   - "/app/node_modules"
    # ports:
    #   - "3001:3000"

  mongo:
    container_name: mongo_backend
    image: mongo
    restart: always
    expose:
      - "27017"
    ports:
      - "5000:5000"
    volumes:
      - backendDB:/data/db
    environment:
      MONGO_DB : Socialmedia_Application
      MONGO_USER : 
      MONGO_PASSWORD : 

volumes:
  backendDB:
    
